name: Coverage

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.17'
      - name: Install CFSSL + Run Test
        #run: echo $GOPATH
        run: go get -d github.com/cloudflare/cfssl/cmd/cfssl && go get -d github.com/cloudflare/cfssl/cmd/cfssljson && make init gencert test
      - name: Upload coverage to Codecov
        run: bash <(curl -s https://codecov.io/bash)